### ISSUE TITLE
Waveguide.update_node() - rebuild node with new params

### ISSUE THREAD

**Issue by demisjohn** [demisjohn/pyFIMM#65]
Same as `Waveguide.buildNode()`, but without creating new nodes - only updates node values (including molab params).

This relies on #64 , so that we can use `get_buildnode_str(  new_nodes=False )`.

**Comment by demisjohn** [comment]
I think I already added a `Waveguide.set_wavelength()` function - if so, this `update_node()` function would be very useful.  Currently I had functions like `set_wavelength()` update the python internal variable AND the fimmwave setting.  with `update_node`, you could instead only update only the python internal, and `update_node` would push those updates to the FimmWave node.

**Comment by estanton22** [comment]
Functionality for updateNode is now incorporated into buildNode within the Waveguide class.

4db592d489b3498f2259f819dd45e0a806a1d26a
